[tool.poetry]
name = "youtube-analytics-project"
version = "0.1.0"
description = ""
authors = ["SergeyRomanov9896 <automag2016@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
